### ISSUE TITLE
server repo url not correct

### ISSUE THREAD

**Issue by lemmebee** [omarahm3/terraform-ec2-server-automation#2]
https://github.com/omarahm3/terraform-ec2-server-automation/blob/c78c43ef3240c36b44b826eb47e58c035fb34d86/scripts/ec2_server_startup.sh#L28

needs to updated with https://github.com/omarahm3/flask-ec2-web-server

**Comment by omarahm3** [comment]
@ehabshaaban Thanks for noting that, fixed on #3
